# https://www.appveyor.com/docs/appveyor-yml

image: Visual Studio 2017

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

shallow_clone: true

environment:
  matrix:
    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.5"
      PYTHON_ARCH: "64"

build_script:
  - set "Path=C:\Python36-x64;%Path%"
  - set "QTDIR=C:\Qt\5.11.2"
  - set "QTKITS=%QTDIR%"
  - python scripts\detail\ci_cd.py

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))